name: sceneview_flutter
description: "A demonstration of how to integrate SceneView in flutter."
version: 0.0.1
homepage: https://github.com/SceneView

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  json_annotation: ^4.9.0
  freezed: ^3.0.6
  freezed_annotation: ^3.0.0

  vector_math: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  build_runner: any

flutter:
  plugin:
    platforms:
      android:
        package: io.github.sceneview.sceneview_flutter
        pluginClass: SceneviewFlutterPlugin

targets:
  $default:
    builders:
      json_serializable:
        options:
          explicit_to_json: true
          field_rename: snake
